# Generated by Django 5.2.6 on 2025-09-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert'), ('success', 'Success')], default='info', max_length=20),
        ),
    ]
